[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[dependencies]
glow = { path = "../../", default-features=false }

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = { version = "0.24", optional = true }
sdl2 = { version = "0.33", optional = true }

[features]
default = ["web-sys"]
web-sys = ["web_sys", "wasm-bindgen", "glow/web-sys"]
window-sdl2 = ["sdl2", "glow/sdl2"]
window-glutin = ["glutin", "glow/glutin"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features=["console"], optional = true }
wasm-bindgen = { version = "0.2", optional = true }
